version: "3.8"

services:
  mongodb:
    image: danaespentz/mongo:latest
    restart: always
    container_name: mongodb 
    ports:
    - 27017:27017
    volumes:
    - ./mongodb/data:/data/db

  mineio:
    image: danaespentz/mineio_mineio:latest
    restart: always 
    container_name: mineio 
    depends_on: 
      - mongodb
    ports:
      - 3000:3000
    environment: 
      - SERVER_PORT=3000
      - CONNECTIONSTRING=mongodb+srv://root:root@cluster0.ela8ynl.mongodb.net/